pdf2mybib done

diff --git a/scripts/.scripts/pdf2myBib b/scripts/.scripts/pdf2myBib
--- a/scripts/.scripts/pdf2myBib
+++ b/scripts/.scripts/pdf2myBib
@@ -1,12 +1,40 @@
-#!/bin/bash
+#!/bin/sh
+move_file() {
+    find ~/Documents/Sci-Bib/. | grep -wq "${1}.pdf"
+    if [ $? -eq 1 ]
+    then
+        mv "${PWD}/${2}" "$HOME/Documents/myBib/pdfs/${1}.pdf"
+    else
+            echo "${1}.pdf was found. Abort..."
+            exit 1
+    fi
+}
 
+use_doi=false
+use_ayt=false
 while getopts d:a:y:t: opt; do
     case $opt in
         d)
             doi=$OPTARG
+            use_doi=true
+            use_ayt=false
+            ;;
+        a)
+            author=$OPTARG
+            use_ayt=true
+            use_doi=false
+            ;;
+        y)
+            year=$OPTARG
+            use_ayt=true
+            use_doi=false
+            ;;
+        t)
+            title=$OPTARG
+            use_ayt=true
+            use_doi=false
             ;;
         ?)
-            echo "usage: "
             exit 1
             ;;
     esac
@@ -14,22 +42,25 @@ done
 
 shift $((OPTIND-1))
 
-
-
-    
-check_file() {
-    find ~/Documents/Sci-Bib/. | grep -i -q ${1}
-    if [ $? -eq 0 ]
-    then
-            old_file=$(find ~/Documents/Sci-Bib/. | grep -i ${1})
-            get_old_info $old_file
-            mv $old_file "old""$key"".txt"
-            make_file
-            if [ -z ${old_pdf+x} ]; then : ; else mv "$old_pdf" "$key"".pdf" ; fi
-            exit 1
-    else
-            :   
-    fi
-}
-
-
+if [ "$use_doi" = true ]
+then
+    bib=$(doi2bib $doi | bibtool -R -r biblatex)
+    key=$(echo $bib | pcregrep -M -o "\S+(\d\d\d\d|ohneJahr)(?=,)")
+    echo $bib | bib2myBib
+    move_file $key $1
+    exit 0
+elif [ "$use_ayt" = true ]
+then
+    #pass over to bib2myBib
+    string="@article{articlekey, Author = {${author}, Title = {${title}}, Year = ${year}}}"
+    bib=$(echo $string | bibtool -R -r biblatex)
+    key=$(echo $bib | pcregrep -M -o "\S+(\d\d\d\d|ohneJahr)(?=,)")
+    echo $bib | bib2myBib
+    move_file $key $1
+else
+    doi=$(pdf2doi $1)
+    bib=$(doi2bib $doi | bibtool -R -r biblatex)
+    key=$(echo $bib | pcregrep -M -o "\S+(\d\d\d\d|ohneJahr)(?=,)")
+    echo $bib | bib2myBib
+    move_file $key $1
+fi
